### PR TITLE
Update header.js

### PR DESCRIPTION
**Pull request by ColinRTaylor**
does this contextType?

### CODE REVIEW

**Comment by ColinRTaylor** [comment]
@kotojo any update on this?

**Comment by kotojo** [comment]
I'm gonna need you to pull the repo to find out if it works before I merge it.

**Comment by ColinRTaylor** [comment]
cc @jeowulf

**Comment by ColinRTaylor** [comment]
@kotojo maybe if you had a CI setup w/ this app I wouldn't have to do that

**Comment by ColinRTaylor** [comment]
🔥

**Pull request merged**
